-- 코드를 입력하세요
SELECT PD.PRODUCT_CODE,
    SUM(OS.SALES_AMOUNT * PD.PRICE) AS SALES
FROM PRODUCT AS PD
    JOIN OFFLINE_SALE AS OS
    ON PD.PRODUCT_ID = OS.PRODUCT_ID
GROUP BY PD.PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE