-- 코드를 입력하세요
SELECT DISTINCT(CI.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR AS CI
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CH
    ON CI.CAR_ID = CH.CAR_ID
WHERE CI.CAR_TYPE = '세단' AND MONTH(START_DATE) = 10
ORDER BY CI.CAR_ID DESC