-- 코드를 입력하세요
SELECT II.INGREDIENT_TYPE, SUM(FS.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF AS FS
    JOIN ICECREAM_INFO AS II
    ON FS.FLAVOR = II.FLAVOR
GROUP BY INGREDIENT_TYPE
ORDER BY TOTAL_ORDER